### ISSUE TITLE
Character limit on tasks

### ISSUE THREAD

**Issue by csprance** [csprance/MisRCON#19]
Find out the cause of character limit and if it's not able to be increased limit the amount of characters that can be added to a task to prevent this error from happening.

Reported in https://github.com/csprance/MisRCON/issues/18

**Comment by Xi57** [comment]
Hey Chris, I've been using the program extensively and I've come to the conclusion that the underlying cause of the issue was not a character limit that was cutting off the end of a sent message, but instead in my case a semicolon ";" symbol that did this. For example, if you sent a message, task or not, saying "Admin Message; All Players..", it would only send "Admin message", and remove any text following the semicolon. Interesting development, hope this helps!

**Comment by csprance** [comment]
fixed in v3
